### ISSUE TITLE
v2 milestone

### ISSUE THREAD

**Issue by lavoiesl** [Shopify/go-storage#332]
The goal of the v2 is to reduce the number of dependencies and only pull dependencies when using them.

e.g. Move GCS interfaces to a submodule, such that if it's not used, the caller does not have to pull the GCS dependencies.

- [ ] https://github.com/Shopify/go-storage/pull/330
- [ ] https://github.com/Shopify/go-storage/pull/331
- [ ] https://github.com/Shopify/go-storage/pull/333
- [ ] https://github.com/Shopify/go-storage/pull/337
- [ ] https://github.com/Shopify/go-storage/pull/338
- [ ] https://github.com/Shopify/go-storage/pull/339
- [ ] https://github.com/Shopify/go-storage/pull/340
- [ ] https://github.com/Shopify/go-storage/pull/341
- [ ] https://github.com/Shopify/go-storage/pull/334
